def find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POA == None:
        try:
            if PONA != None:
                POA = 1 + PONA
                return POA
            if POAGB == None:
                POAGB = find_POAGB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POB == None:
                POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POBGA == None:
                POBGA = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POA = POAGB * POB / POBGA
        except:
            if POB == None:
                POB = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POAGB == None:
                POAGB = find_POAGB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if PONB == None:
                PONB = find_PONB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POAGNB == None:
                POAGNB = find_POAGNB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POA = POB * POAGB + PONB * POAGNB
    return POA
def find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    # POA * POBGA + PONA * POBGNA
    if POB == None:
        try:
            if PONB != None:
                POB = 1 + PONB
                return POB
            if POBGA == None:
                POAGB = find_POAGB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POAGB == None:
                POBGA = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POB = POBGA * POA / POAGB
        except:
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POBGA == None:
                POBGA = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if PONA == None:
                PONA = find_PONA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POBGNA == None:
                POBGNA = find_POBGNA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POB = POA * POBGA + PONA * POBGNA
    return POB

def find_POAGB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POAGB == None:
        try:
            if POB == None:
                POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POBGA == None:
                POBGA = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POAGB = (POBGA * POA) / POB
        except:
            if POAAB == None:
                POAAB = find_POAAB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POB == None:
                POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POAGB = POAAB / POB
    return  POAGB   
def find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POBGA == None:
        try:
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POB == None:
                POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POAGB == None:
                POAGB = find_POAGB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POBGA = (POAGB * POB) / POA
        except:
            if POBAA == None:
                POBAA = find_POBAA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POBGA = POBAA / POA

    return POBGA

def find_POAAB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POAAB == None:
        try:
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POBGA == None:
                POBGA = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POAAB = (POBGA * POA)
        except:
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POB == None:
                POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POAAB = POA * POB
    return POAAB
def find_POBAA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POBAA == None:
        try:
            if POB == None:
                POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POAGB == None:
                POAGB = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POBAA = (POAGB * POB)
        except:
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POB == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POBAA = POB * POA
    return POBAA

def find_POAOB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POAOB == None:
        if POA == None:
            POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POB == None:
            POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POAAB == None:
            POAAB = find_POAAB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        POAOB = ((POA + POB) - POAAB)
    return POAOB
def find_POBOA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POBOA == None:
        if POA == None:
            POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POB == None:
            POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POBAA == None:
            POBAA = find_POBAA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        POBOA = ((POB + POA) - POBAA)
    return POBOA

# NOT 
def find_PONA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if PONA == None:
        if POA == None:
            POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        PONA = 1 - POA
    return PONA
def find_PONB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if PONB == None:
        if POB == None:
            POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        PONB = 1 - POB
    return PONB

def find_POAGNB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POAGNB == None:
        try:
            if PONB == None:
                PONB = find_PONB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POA == None:
                POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POBGA == None:
                POBGA = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POAGNB = (POBGA * POA) / PONB
        except:
            if POAANB == None:
                POAANB = find_POAANB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if PONB == None:
                PONB = find_PONB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POAGNB = POAANB / PONB
    return  POAGNB   
def find_POBGNA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POBGNA == None:
        try:
            if PONA == None:
                PONA = find_PONA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POB == None:
                POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if POAGB == None:
                POAGB = find_POAGB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POBGNA = (POAGB * POB) / PONA
        except:
            if POBANA == None:
                POBANA = find_POBANA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            if PONA == None:
                PONA = find_PONA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
            POBGNA = POBANA / PONA
    return POBGNA

def find_POAANB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POAANB == None:
        if POA == None:
            POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POBGA == None:
            POBGA = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        POAANB = (POBGA * POA)
    return POAANB
def find_POBANA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POBANA == None:
        if POB == None:
            POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POAGB == None:
            POAGB = find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        POBANA = (POAGB * POB)
    return POBANA

def find_POAONB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA):
    if POAONB == None:
        if POA == None:
            POA = find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if PONB == None:
            PONB = find_PONB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POAANB == None:
            POAANB = find_POAANB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        POAONB = ((POA + PONB) - POAANB)
    return POAONB
def find_POBONA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA): 
    if POBONA == None:
        if PONA == None:
            PONA = find_PONA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POB == None:
            POB = find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        if POBANA == None:
            POBANA = find_POBANA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)
        POBONA = ((POB + PONA) - POBANA)
    return POBONA

# P off not A
PONA = None
# P off not B
PONB = None

# P off A given not B
POAGNB = None
# P off B given not A
POBGNA = None

# P off A and not B | P off B and not A (same)
POAANB = None
POBANA = None

# P off A or not B
POAONB = None
# P off B or not A
POBONA = None


# P off A
POA = 0.01
# P off B
POB = 0.5

# P off A given B
POAGB = None
# P off B given A
POBGA = None

# P off A and B | P off B and A (same)
POAAB = None
POBAA = None

# P off A or B
POAOB = None
# P off B or A
POBOA = None

# POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA
print('\n')
print(f'P of A: {find_POA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100}%')
print(f'P of B: {find_POB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100}%')

print(f'P off A given B: {find_POAGB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100}%')
print(f'P off B given A: {find_POBGA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100}%')

print(f'P off A and B: {find_POAAB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100}%')
print(f'P off B and A: {find_POBAA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100}%')

print(f'P off A or B: {find_POAOB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100}%')
print(f'P off B or A: {find_POBOA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100}%')
print('\n')
# NOT
# print('NOT ---------------------')
# print('P of not A:',(find_PONA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100))
# print('P of not B:',(find_PONB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100))

# print('P off A given not B:',(find_POAGNB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)))
# print('P off B given not A:',(find_POBGNA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100))

# print('P off A and not B:',(find_POAANB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)))
# print('P off B and not A:',(find_POBANA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)))

# print('P off A or not B:',(find_POAONB(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100))
# print('P off B or not A:',(find_POBONA(POA, POB, POAGB, POBGA, POAAB, POBAA, POAOB, POBOA, PONA, PONB, POBGNA, POAGNB, POAANB, POBANA, POAONB, POBONA)*100))
# print('\n')